language: node_js
services:
  - docker
before_install: 
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build --prod
deploy:
  - provider: script
    script: bash ./deploy.sh
    on:
      branch: master
  - provider: script
    script: bash ./deploy.sh
    on:
      branch: develop
  - provider: script
    script: bash ./deploy.sh
    on: 
      tags: true
      branch: master